### ISSUE TITLE
连发可否加一个美服客户端检测？

### ISSUE THREAD

**Issue by Lucaxuor** [mouyase/DNFAutoFire#10]
貌似是因为下面这行代码检测不到游戏本体
我看到这行代码 " WinActivate, ahk_class 地下城与勇士"

因为我不会改exe

美服的客户端是 DFO.exe

煞笔棒子的后台程序河蟹了SET_AHK生产的ahk.exe, 会被客户端自动断网
自用的ahk 
send {？}
游戏客户端无法检测到， 但是聊天框里可以连发出来晕

如果能加入一个美服客户端检测支持真的是太好了, 好人一生平安

**Comment by mouyase** [comment]
最新版已经添加了
